### ISSUE TITLE
Move our GitHub repo to DOI Ownership

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/doi-extractives-data#2777] opened 2018-04-16 10:42 UTC
We need to move our GitHub repo to DOI Ownership before 18F transitions off the project.

There is already a DOI GitHub at The U.S. Department of the Interior organization. 

- [x] Ensure permissions are set up right for move

- [x] Evaluate for any other issues of making the move (e.g. federalist)

- [x] Move the repo

**Comment by alexpandel** [comment] 2018-04-23 17:52
@jennmalcolm what's the next step on this? It would be helpful to know what you need from 18F on this before I head out on vacation if possible...

**Comment by jennmalcolm** [comment] 2018-05-14 13:01
We have set up an ONRR organization on GitHub and @brentryanjohnson has had a conversation with Federalist about the move. 

Next step: @jenniferthibault to reach out to colleagues at 18F for best practices when transitioning repo.

**Comment by jenniferthibault** [comment] 2018-05-14 14:49
The person I was thinking to reach out to is OOO until Weds this week for a training

What I remember from my FEC experience is that we needed to have at least one person who has both ownership permissions on the sending repo, and permission to create repos in the landing org. 
That's confirmed by these [GitHub instructions](https://help.github.com/articles/transferring-a-repository-owned-by-your-organization/)

After the transfer, the new owner made a new GitHub group in their org and put the 18F team members who needed to contribute to the project in it. That handled the permissions and access issue easily.

I don't have permission in the repo currently to see who has what level of power, @jennmalcolm do you? You'd be able to tell if on the landing page of the repo, you can see a "Settings" tab. Click into there to see who has what permissions.
<img width="790" alt="screen shot 2018-05-14 at 9 55 09 am" src="https://user-images.githubusercontent.com/11636908/40004490-d1545bde-5763-11e8-8b38-981f3d50fca6.png">

**Next steps:**
@brentryanjohnson can you help outline what additional info we need to find out? That will help me know who we should be reaching out to.

—

**Comment by brentryanjohnson** [comment] 2018-05-16 17:43
@jennmalcolm I think you're still the only admin in the org, if I correctly understand GitHub permissions. I think members can contribute to repos, but can't administer the organization or the repositories themselves.

![admins and members in github org](https://user-images.githubusercontent.com/32855580/40133838-bcb32028-58f5-11e8-916b-5c8f1c81df50.png)

**Comment by brentryanjohnson** [comment] 2018-05-16 17:46
To qualify my previous comment, here's the [GitHub guidance](https://help.github.com/articles/transferring-a-repository-owned-by-your-organization/):

> If Allow members to delete or transfer repositories for this organization has been disabled in the organization, only organization owners can transfer organization repositories.

**Comment by jennmalcolm** [comment] 2018-05-16 17:52
Ok, so the comment about all ONRR people being admins was for the current repo. 

As for the ONRR org, Ryan is right. I thought I had already made Ryan an owner as well, but clearly I failed. I have tried again. @brentryanjohnson, let me know if you're still not getting owner privileges.

**Comment by brentryanjohnson** [comment] 2018-05-16 17:54
Apologies for the misunderstanding, @jennmalcolm. Yes, it looks like it worked.

**Comment by jenniferthibault** [comment] 2018-05-17 21:52
From questions above:

## If we transfer the repo to ONRR's org, what kind of runway do we need to provide Federalist to point to the new location? How long will it take for Federalist to read off the master branch in the new location?

- @wslack can you speak to this?

## Is it advisable (or even possible) to fork the repo instead, and will the fork retain the issues and PRs in the new org?

This is possible, but I'm getting the gist that it's not advisable — you do want to own it completely! If the concerns driving this were primarily about retaining history, collaborators, issues, and PRs, we have good news! That stuff all comes over with transfers.
 
From :octocat:  [About repository transfers](https://help.github.com/articles/about-repository-transfers/)

> When you transfer a repository, its issues, wiki, stars, and watchers are also transferred.

> All Git information about commits, including contributions, are preserved. All of the issues and pull requests remain intact when transferring a repository. 

> The original owner of the repository is added as a collaborator on the transferred repository. Other collaborators to the transferred repository remain intact.
 - Though some corrections might be needed to adjust permission-levels in the new environment

From  :octocat:  [Transferring a repository owned by your organization](https://help.github.com/articles/transferring-a-repository-owned-by-your-organization/) 
> Once a repository is transferred to an organization, the organization's default repository permission settings will apply to the transferred repository. For example, if your default repository permission settings allow organization members read/write access, then all organization members can clone, pull, and push all repositories, including transferred repositories.


## What other considerations do we need to think about? We know we'll need to reconfigure our Waffle board, for example. Any links we'll need to address?

- If there are third-party tools integrated with the repo, make sure that they are approved for use in the DOI org. This _might_ include Hound, Circle CI (and others I don't yet know you use)

Other relevant parts of guidance:




From :octocat:  [About repository transfers](https://help.github.com/articles/about-repository-transfers/)

> All links to the previous repository location are automatically redirected to the new location. When you use git clone, git fetch, or git push on a transferred repository, these commands will redirect to the new repository location or URL. However, to avoid confusion, we strongly recommend updating any existing local clones to point to the new repository URL. You can do this by using git remote on the command line: `git remote set-url origin new_url`
> For more information, see "[Changing a remote's URL](https://help.github.com/articles/changing-a-remote-s-url)".

## We would (temporarily, at least) have two instances of the same repo, which could cause confusion.

After transferring, we can close out unfinished PRs to the old repo, and archive it, which puts it in a read-only state. It's _SUPER_ easy to unarchive it if we need to go back to edit any documentation to make more clear that it's archived, then point to the new one.

**Comment by jenniferthibault** [comment] 2018-05-17 22:29
And!

Here are two tickets with checklists outlining FEC's github repo transfer tasks
https://github.com/fecgov/fec-transition/issues/155
https://github.com/fecgov/fec-cms/issues/1836

**Comment by brentryanjohnson** [comment] 2018-05-17 22:55
This is great, @jenniferthibault. Thank you for the help!

**Comment by brentryanjohnson** [comment] 2018-05-18 15:58
I noticed our [`package.json`](https://github.com/18F/doi-extractives-data/blob/dev/package.json) file contains a value for the repository path and associated URL (for issues). We should keep that file on the radar when we transfer to ONRR org.

**Comment by wslack** [comment] 2018-05-18 22:30
> If we transfer the repo to ONRR's org, what kind of runway do we need to provide Federalist to point to the new location? How long will it take for Federalist to read off the master branch in the new location?

If you coordinate the time with me, I can repoint this right after it finishes building in the new location. (remember to also set the custom URL as well)

**Comment by brentryanjohnson** [comment] 2018-06-11 22:17
As we move closer to transitioning this repo to the ONRR org, here's a list of repo references in various files in our repo:

- [Pull request template](https://github.com/18F/doi-extractives-data/blob/d7658a594991c9c9b6f0b24019274afc9a759ae3/.github/PULL_REQUEST_TEMPLATE.md)
- [`federalist-preview.rb`](https://github.com/18F/doi-extractives-data/blob/39166c3c4fc4191acb1b7c66d1a2b2c91106b6c9/_plugins/federalist-preview.rb)
- [README](https://github.com/18F/doi-extractives-data/blob/11e03adccad7404814360dbb17dc05522583003b/README.md)
- [Style guide footer (site version link)](https://github.com/18F/doi-extractives-data/blob/d7228fbdaa10ddb9ca8276ac9e6c80719add172a/nrrd-design-system/components/components/global-footer/global-footer.hbs) (this _may_ redirect on its own)
- [Footer (site version link)](https://github.com/18F/doi-extractives-data/blob/70d4acb413b7556328d19f883e7e92441321067e/_includes/layout/footer.html)
- [Data README](https://github.com/18F/doi-extractives-data/blob/83a59b07725df049e55794f0c797bcbba1ed5b29/data/README.md)
- [`package.json`](https://github.com/18F/doi-extractives-data/blob/d91a007893a55e9bdd7b085ceff55fdc60a84022/package.json)
- [GDP README](https://github.com/18F/doi-extractives-data/blob/842b9c54646bd7c3b891a65b8a30bc0d57c85b4e/data/gdp/README.md) (this _may_ redirect on its own)
- [Icons README](https://github.com/18F/doi-extractives-data/blob/204ff0f6685be6a0d9fd5b00fb3206889256418a/nrrd-design-system/components/components/icons/README.md)
- [Disbursements README](https://github.com/18F/doi-extractives-data/blob/14e511cd3be1ff9229ef63500b68aa9f8f28e859/data/disbursements/README.md)
- [`_sass/blocks/_banner.scss`](https://github.com/18F/doi-extractives-data/blob/0276aa1a1069ffe6e54c997c97aef4503ece3b07/_sass/blocks/_banner.scss)
- [Revenue README](https://github.com/18F/doi-extractives-data/blob/fc43a18514c6b0964fa3b7be54f94a530f04f40f/data/revenue/README.md)
- [`_downloads/default.md`](https://github.com/18F/doi-extractives-data/blob/b7c0dc653056640ef5ab9abb1440c0e8114e5cdc/_downloads/default.md)
- [`CONTRIBUTING.md`](https://github.com/18F/doi-extractives-data/blob/97a8232f8d80baf8a8ca7b5708214cdfd2dbca57/CONTRIBUTING.md)
- [Style guide hero component](https://github.com/18F/doi-extractives-data/blob/447fe514367ad80abb19c67b09c89e5f06beb093/nrrd-design-system/components/components/hero-ribbons/hero-ribbons.hbs)
- [`_downloads/disbursements.md`](https://github.com/18F/doi-extractives-data/blob/b7c0dc653056640ef5ab9abb1440c0e8114e5cdc/_downloads/disbursements.md)
- [`_downloads/federal-production.md`](https://github.com/18F/doi-extractives-data/blob/b7c0dc653056640ef5ab9abb1440c0e8114e5cdc/_downloads/federal-production.md)
- [`_downloads/federal-revenue-by-company.md`](https://github.com/18F/doi-extractives-data/blob/b7c0dc653056640ef5ab9abb1440c0e8114e5cdc/_downloads/federal-revenue-by-company.md)
- [`_downloads/federal-revenue-by-location.md`](https://github.com/18F/doi-extractives-data/blob/b7c0dc653056640ef5ab9abb1440c0e8114e5cdc/_downloads/federal-revenue-by-location.md)

**Comment by brentryanjohnson** [comment] 2018-06-15 15:57
We'll likely need to change the remote URL in our local `git` instances when we transition.

- [Changing a remote's URL](https://help.github.com/articles/changing-a-remote-s-url/)

**Closed** 2018-06-20 16:03 UTC
Labels: workflow:in-sprint
