### ISSUE TITLE
Add Documentation for Sales Year Data

### ISSUE THREAD

**Issue by mentastc** [ONRR/doi-extractives-data#3743] opened 2019-03-05 17:32 UTC
Similar to the the data sets we will need to create documentation for the sales year data set. This will include adding:

- Standardizing the data fields in the excel document
-Data checks 
-Steps to updating the data file

**Comment by usEITI** [comment] 2019-03-08 13:58
BSEE explains it on their page as follows
Notes: 
1) The figures on this page are total oil and gas production volumes removed from the ground. Sales volumes will differ slightly from production volumes for any given month/year due to fuel, flare, and vent volumes, or sales which occur in a different month from the production month. All production figures on this page are subject to revision. 
2) Effective January 1, 2018, monthly reinjected gas volumes will no longer be reported as gas production volumes in the Alaska OCS Region.

**Comment by jennmalcolm** [comment] 2019-10-15 12:28
This is what you're doing in #3744 right @mentastc? Please close this issue if confirmed.

**Closed** 2019-10-30 15:09 UTC
Labels: p4: Low
